services:
  flask-backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production 
    command: python3 app.py
    platform: linux/amd64
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - START_XVFB=false
      - SE_NODE_MAX_SESSIONS=10
      - JAVA_OPTS=-XX:ActiveProcessorCount=5
    ports:
      - "4444:4444"
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5